# Generated by Django 5.1.3 on 2025-05-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocupacao", models.CharField(max_length=255)),
                ("faixa_salarial", models.CharField(max_length=255)),
                ("possui_reserva", models.BooleanField()),
                ("costuma_investir", models.BooleanField()),
                ("unica_renda", models.BooleanField()),
                ("endividamento", models.CharField(max_length=255)),
                ("interesse_no_app", models.IntegerField()),
                ("expectativa", models.IntegerField()),
            ],
        ),
    ]
